### ISSUE TITLE
Not writing default file

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/Packer#1]
First time messing about with packer and it wont write the default profile, not sure why. Can just manually get around this but thought I would bring this up to you here. Tried on all my chars though that shouldn't matter, and i loaded/unloaded a couple times too, including after client restart.

![Wigmasterflex_2022 03 27_182459](https://user-images.githubusercontent.com/66495755/160305852-5b80d6eb-58c6-4cf4-8bc0-ab88b2dceb7f.png)

**Comment by ThornyFFXI** [comment]
Fixed in 1.12.
